simulation:
  duration_sec: 1000
  net_latency_sec: 0.01

logic:
  lottery_interval_sec: 1
  sender_prob: 0.01
  
mixnet:
  num_nodes: 5
  transmission_rate_per_sec: 10
  peering_degree: 6
  max_mix_path_length: 3
