simulation:
  duration_sec: 1000
  net_latency_sec: 0.01

logic:
  sender_lottery:
    interval_sec: 1
    probability: 0.01
    seed: 10
  
mixnet:
  num_nodes: 5
  transmission_rate_per_sec: 10
  peering:
    degree: 6
  mix_path:
    max_length: 3
    seed: 3
