[workspace]
resolver = "2"
members = [ "cl", "ledger", "proof_statements", "risc0_proofs"]

# Always optimize; building and running the risc0_proofs takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
