from libp2p.typing import TProtocol

PROTOCOL_ID = TProtocol("/nomosda/1.0.0")
MAX_READ_LEN = 2**32 - 1

DEFAULT_DATA_SIZE = 1024
DEFAULT_SUBNETS = 256
DEFAULT_NODES = 32
DEFAULT_SAMPLE_THRESHOLD = 12

DEBUG = False
