name: Spec tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.12'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build and install eth-specs
        run: ./install-eth-specs.sh
      - name: Run tests
        run: python -m unittest
